name: format-pr
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - main

    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: julia-actions/julia-format@v4
        with:
          version: '1'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Format code
          title: 'Format code of branch "main"'
          branch: format-main
          delete-branch: true
          labels: format
          reviewers: mofeing
          base: main
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
